name: py_data_viz
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip:
    - altair==5.1.2
    - ipython==8.17.2
    - matplotlib==3.8.1
    - numpy==1.26.1
    - openpyxl==3.1.2
    - pandas==2.1.2
    - pytest==7.4.3
    - pytest-cov==4.1.0
